pipeline{
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK21"
    }
    stages{
        stage('Fetch Code') {
            steps{
                git branch: 'release/backend', url: 'https://github.com/MithunKumar08/ExpenseTracker.git'
            }
        }
        stage('Maven Clean Install') {
            steps{
                sh 'mvn clean install -DskipTests -f expensetracker/pom.xml'
            }
            post {
                success{
                    echo "Archiving artifacts"
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
        stage('CheckStyle Analysis'){
            steps{
                sh 'mvn checkstyle:checkstyle -f expensetracker/pom.xml'
            }
        }
        stage('Sonar Code Analysis'){
            environment{
                scannerHome = tool 'sonar6.2'
            }
            steps{
                withSonarQubeEnv('sonarserver'){
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=expenseTracker \
                        -Dsonar.projectName=expenseTracker \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.source=src/main/java \
                        -Dsonar.java.binaries=expensetracker/target/classes \
                        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                    '''
                }
            }
        }
        stage('Quality Gate'){
            steps{
                timeout(time:1, unit: 'HOURS'){
                   waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Upload Artifacts'){
            steps{
                nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: '172.31.6.223:8081',
                        groupId: 'QA',
                        version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                        repository: 'expense-repo',
                        credentialsId: 'nexuslogin',
                        artifacts: [
                            [artifactId: 'expenseapp',
                             classifier: '',
                             file: 'target/expensetracker-0.0.1-SNAPSHOT.jar',
                             type: 'jar']
                        ]
                     )
            }
        }
    }
}